<a href="https://colab.research.google.com/github/naren2704/copy-file/blob/main/Data%20Sciene.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

IMPORT


NAREN

numpy version



In [1]:
pip install numpy

In [2]:
import numpy as np

In [5]:
np.__version__

'1.25.2'

In [6]:
a=np.array(1)
print(a)

1


1 DIMENSIONAL ARRAY

In [7]:
b=np.array([1,2,3])
print(b)

[1 2 3]


2 DIMENSIONAL ARRAY

In [8]:
c=np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


3 DIMENSIONAL ARRAY

In [9]:
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


CHECKING ARRAY DIMENSION

In [11]:
np.ndim(a)


0

In [12]:
np.ndim(b)

1

In [13]:
np.ndim(c)

2

In [15]:
np.ndim(d)

3

TO CHANGE DIMENSION


In [19]:
a=np.array([1,2,3,4,5,6],ndmin=2)
print(a)

[[1 2 3 4 5 6]]


ACCESSING THE ELEMENT



1 DIMENSIONAL ELEMENT

In [18]:
e=np.array([1,2,3,4,5,6])
e[3]

4

2 DIMENSIONAL ELEMENT


In [26]:
f=np.array([[1,2,3,4,5],[6,7,8,9,10]])
f[1,2]

8

In [27]:
f[0,3]

4

NEGATIVE INDEXING


In [28]:
f[0,-2]

4

In [34]:
print(f[0,3:],f[1,4:]) #to get 4 , 5 and 10

[4 5] [10]
