<a href="https://colab.research.google.com/github/naren2704/copy-file/blob/main/Data%20Sciene.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

IMPORT


NAREN

numpy version



In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.25.2'

In [ ]:
a=np.array(1)
print(a)

1


1 DIMENSIONAL ARRAY

In [ ]:
b=np.array([1,2,3])
print(b)

[1 2 3]


2 DIMENSIONAL ARRAY

In [ ]:
c=np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


3 DIMENSIONAL ARRAY

In [ ]:
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


CHECKING ARRAY DIMENSION

In [ ]:
np.ndim(a)


0

In [ ]:
np.ndim(b)

1

In [ ]:
np.ndim(c)

2

In [ ]:
np.ndim(d)

3

TO CHANGE DIMENSION


In [ ]:
a=np.array([1,2,3,4,5,6],ndmin=2)
print(a)

[[1 2 3 4 5 6]]


ACCESSING THE ELEMENT



1 DIMENSIONAL ELEMENT

In [ ]:
e=np.array([1,2,3,4,5,6])
e[3]

4

2 DIMENSIONAL ELEMENT


In [ ]:
f=np.array([[1,2,3,4,5],[6,7,8,9,10]])
f[1,2]

8

In [ ]:
f[0,3]

4

NEGATIVE INDEXING


In [ ]:
f[0,-2]

4

In [ ]:
print(f[0,3:],f[1,4:]) #to get 4 , 5 and 10

[4 5] [10]


EXERCISE-1

In [7]:
import numpy as np
arr5=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(arr5)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [8]:
arr5[1:4,1:4]


array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [9]:
arry=np.arange(1,26).reshape(5,5)
upd=arry[1:4,1:4]
print(upd)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [10]:
for x in arry:
  if np.array_equal(x, upd):
    print("")
print(arry)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


SERIES


In [3]:
import pandas as pd
a=[1,2,3,4,5]
b=pd.Series(a)
print(b[1])
c=pd.Series(a,index=['a','b','c','d','e'])
print(c['d'])


2
4


In [4]:
fd={
    'a':1,
    'b':2,
    'c':3
}
d=pd.Series(fd)
d


print(d['b'])

2
